import { describe, it, expect, beforeEach, vi } from "vitest";
import { LessonBuilderService, CreateDraftInput } from "../application/lessonBuilderService";
import { FakeDraftRepository, FakeClock, FakeIdGenerator } from "./fakes";
import { PipelineState, StepState, LessonDraft } from "../domain/types";
import { ValidationError, BusinessError, InfrastructureError, BaseWorkflowError } from "../domain/errors";
import { PublishLessonCommand } from "../application/commands";

describe("LessonBuilderService Facade Layer Unit Tests", () => {
  let fakeDraftRepository: FakeDraftRepository;
  let fakeIdGenerator: FakeIdGenerator;
  let fakeClock: FakeClock;
  let mockCommandDispatcher: any;
  let mockWorkflowEngine: any;
  let service: LessonBuilderService;

  beforeEach(() => {
    fakeDraftRepository = new FakeDraftRepository();
    fakeIdGenerator = new FakeIdGenerator();
    fakeClock = new FakeClock();

    mockCommandDispatcher = {
      dispatch: vi.fn().mockResolvedValue(undefined),
    };

    mockWorkflowEngine = {
      stepRegistry: {} as any,
      commandDispatcher: mockCommandDispatcher,
      eventDispatcher: {} as any,
      runner: {} as any,
      executePipeline: vi.fn().mockResolvedValue(undefined),
      executeStep: vi.fn().mockResolvedValue(undefined),
      resumePipeline: vi.fn().mockResolvedValue(undefined),
      pausePipeline: vi.fn().mockResolvedValue(undefined),
      cancelPipeline: vi.fn().mockResolvedValue(undefined),
    };

    service = new LessonBuilderService(
      mockWorkflowEngine,
      fakeDraftRepository,
      mockCommandDispatcher,
      fakeIdGenerator,
      fakeClock
    );
  });

  describe("createDraft", () => {
    const validInput: CreateDraftInput = {
      metadata: {
        level: "N4",
        lessonId: 10,
        titleVi: "Bài 10",
        titleEn: "Lesson 10"
      },
      input: {
        vocabulary: [
          { id: "v1", hiragana: "ねこ", romaji: "neko", meaningVi: "con mèo" }
        ],
        grammar: [
          { id: "g1", pattern: "～たい", meaningVi: "muốn", explanationVi: "diễn tả mong muốn", examples: [] }
        ]
      },
      aiModel: "gemini-3.5-flash",
      promptVersion: "1.0",
      createdById: "user-123"
    };

    it("should successfully create and save a new draft with correct defaults", async () => {
      const draft = await service.createDraft(validInput);

      expect(draft).toBeDefined();
      expect(draft.id).toBe("id-1"); // Generated by FakeIdGenerator
      expect(draft.schemaVersion).toBe(1);
      expect(draft.aiModel).toBe("gemini-3.5-flash");
      expect(draft.promptVersion).toBe("1.0");
      expect(draft.pipelineState).toBe(PipelineState.DRAFT);
      expect(draft.currentStepId).toBeNull();
      expect(draft.steps).toEqual({});
      expect(draft.context.metadata.level).toBe("N4");
      expect(draft.context.metadata.lessonId).toBe(10);
      expect(draft.context.metadata.titleVi).toBe("Bài 10");
      expect(draft.context.metadata.titleEn).toBe("Lesson 10");
      expect(draft.context.input.vocabulary).toHaveLength(1);
      expect(draft.context.input.grammar).toHaveLength(1);
      expect(draft.createdById).toBe("user-123");
      expect(draft.createdAt).toBe(fakeClock.now());
      expect(draft.updatedAt).toBe(fakeClock.now());

      // Verify repository save
      const saved = await fakeDraftRepository.getById(draft.id);
      expect(saved).not.toBeNull();
      expect(saved!.id).toBe(draft.id);
    });

    it("should use defaults if optional fields are not provided", async () => {
      const minimalInput: CreateDraftInput = {
        metadata: {
          level: "N5",
          lessonId: 1,
          titleVi: "Bài 1"
        },
        input: {
          vocabulary: [],
          grammar: []
        }
      };

      const draft = await service.createDraft(minimalInput);
      expect(draft.aiModel).toBe("gemini-3.5-flash");
      expect(draft.promptVersion).toBe("1.0");
      expect(draft.createdById).toBe("system");
    });

    it("should throw ValidationError if metadata is missing", async () => {
      const invalid = { input: { vocabulary: [], grammar: [] } } as any;
      await expect(service.createDraft(invalid)).rejects.toThrow(ValidationError);
    });

    it("should throw ValidationError if level is missing", async () => {
      const invalid = { metadata: { lessonId: 1, titleVi: "Bài" }, input: { vocabulary: [], grammar: [] } } as any;
      await expect(service.createDraft(invalid)).rejects.toThrow(ValidationError);
    });

    it("should throw ValidationError if lessonId is missing", async () => {
      const invalid = { metadata: { level: "N5", titleVi: "Bài" }, input: { vocabulary: [], grammar: [] } } as any;
      await expect(service.createDraft(invalid)).rejects.toThrow(ValidationError);
    });

    it("should throw ValidationError if titleVi is missing", async () => {
      const invalid = { metadata: { level: "N5", lessonId: 1 }, input: { vocabulary: [], grammar: [] } } as any;
      await expect(service.createDraft(invalid)).rejects.toThrow(ValidationError);
    });

    it("should throw ValidationError if input is missing", async () => {
      const invalid = { metadata: { level: "N5", lessonId: 1, titleVi: "Bài" } } as any;
      await expect(service.createDraft(invalid)).rejects.toThrow(ValidationError);
    });

    it("should throw ValidationError if vocabulary is not an array", async () => {
      const invalid = {
        metadata: { level: "N5", lessonId: 1, titleVi: "Bài" },
        input: { vocabulary: {}, grammar: [] }
      } as any;
      await expect(service.createDraft(invalid)).rejects.toThrow(ValidationError);
    });

    it("should throw ValidationError if grammar is not an array", async () => {
      const invalid = {
        metadata: { level: "N5", lessonId: 1, titleVi: "Bài" },
        input: { vocabulary: [], grammar: {} }
      } as any;
      await expect(service.createDraft(invalid)).rejects.toThrow(ValidationError);
    });
  });

  describe("updateDraft", () => {
    let existingDraft: LessonDraft;

    beforeEach(async () => {
      existingDraft = {
        id: "draft-111",
        schemaVersion: 1,
        aiModel: "gemini-3.5-flash",
        promptVersion: "1.0",
        pipelineState: PipelineState.DRAFT,
        currentStepId: null,
        steps: {},
        context: {
          metadata: { level: "N5", lessonId: 1, titleVi: "Bài 1" },
          input: { vocabulary: [], grammar: [] },
          validated: { vocabulary: [], grammar: [] },
          tokenized: { vocabularyTokens: {} },
          generated: { vocabularyWithMeanings: [], vocabularyWithExamples: [], grammarWithMeanings: [], grammarWithExamples: [], review: null }
        },
        createdById: "system",
        createdAt: "2026-07-01T00:00:00Z",
        updatedAt: "2026-07-01T00:00:00Z"
      };
      await fakeDraftRepository.create(existingDraft);
    });

    it("should update and save mutable fields of an existing draft", async () => {
      fakeClock.currentTime = "2026-07-12T12:00:00Z";
      const updated = await service.updateDraft("draft-111", {
        aiModel: "gemini-2.5",
        pipelineState: PipelineState.RUNNING
      });

      expect(updated.aiModel).toBe("gemini-2.5");
      expect(updated.pipelineState).toBe(PipelineState.RUNNING);
      expect(updated.id).toBe("draft-111"); // Protected
      expect(updated.createdAt).toBe("2026-07-01T00:00:00Z"); // Protected
      expect(updated.updatedAt).toBe("2026-07-12T12:00:00Z"); // Updated

      const saved = await fakeDraftRepository.getById("draft-111");
      expect(saved!.aiModel).toBe("gemini-2.5");
      expect(saved!.pipelineState).toBe(PipelineState.RUNNING);
    });

    it("should throw BusinessError when updating a non-existent draft", async () => {
      await expect(service.updateDraft("non-existent", { aiModel: "new" })).rejects.toThrow(BusinessError);
    });
  });

  describe("deleteDraft", () => {
    beforeEach(async () => {
      const draft: LessonDraft = {
        id: "draft-delete",
        schemaVersion: 1,
        aiModel: "gemini-3.5-flash",
        promptVersion: "1.0",
        pipelineState: PipelineState.DRAFT,
        currentStepId: null,
        steps: {},
        context: {
          metadata: { level: "N5", lessonId: 1, titleVi: "Bài" },
          input: { vocabulary: [], grammar: [] },
          validated: { vocabulary: [], grammar: [] },
          tokenized: { vocabularyTokens: {} },
          generated: { vocabularyWithMeanings: [], vocabularyWithExamples: [], grammarWithMeanings: [], grammarWithExamples: [], review: null }
        },
        createdById: "system",
        createdAt: "2026-07-01",
        updatedAt: "2026-07-01"
      };
      await fakeDraftRepository.create(draft);
    });

    it("should successfully delete an existing draft", async () => {
      await service.deleteDraft("draft-delete");
      const fetched = await fakeDraftRepository.getById("draft-delete");
      expect(fetched).toBeNull();
    });

    it("should throw BusinessError when deleting a non-existent draft", async () => {
      await expect(service.deleteDraft("non-existent")).rejects.toThrow(BusinessError);
    });
  });

  describe("getDraft & listDrafts", () => {
    let d1: LessonDraft;
    let d2: LessonDraft;

    beforeEach(async () => {
      d1 = {
        id: "d1",
        schemaVersion: 1,
        aiModel: "model-a",
        promptVersion: "1.0",
        pipelineState: PipelineState.DRAFT,
        currentStepId: null,
        steps: {},
        context: {
          metadata: { level: "N5", lessonId: 1, titleVi: "Bài 1" },
          input: { vocabulary: [], grammar: [] },
          validated: { vocabulary: [], grammar: [] },
          tokenized: { vocabularyTokens: {} },
          generated: { vocabularyWithMeanings: [], vocabularyWithExamples: [], grammarWithMeanings: [], grammarWithExamples: [], review: null }
        },
        createdById: "system",
        createdAt: "2026-07-01",
        updatedAt: "2026-07-01"
      };
      d2 = {
        id: "d2",
        schemaVersion: 1,
        aiModel: "model-b",
        promptVersion: "1.0",
        pipelineState: PipelineState.DRAFT,
        currentStepId: null,
        steps: {},
        context: {
          metadata: { level: "N4", lessonId: 2, titleVi: "Bài 2" },
          input: { vocabulary: [], grammar: [] },
          validated: { vocabulary: [], grammar: [] },
          tokenized: { vocabularyTokens: {} },
          generated: { vocabularyWithMeanings: [], vocabularyWithExamples: [], grammarWithMeanings: [], grammarWithExamples: [], review: null }
        },
        createdById: "system",
        createdAt: "2026-07-01",
        updatedAt: "2026-07-01"
      };
      await fakeDraftRepository.create(d1);
      await fakeDraftRepository.create(d2);
    });

    it("should get draft by ID", async () => {
      const draft = await service.getDraft("d1");
      expect(draft).toEqual(d1);
    });

    it("should throw BusinessError if draft is not found", async () => {
      await expect(service.getDraft("non-existent")).rejects.toThrow(BusinessError);
    });

    it("should list all drafts", async () => {
      const list = await service.listDrafts();
      expect(list).toHaveLength(2);
      expect(list.map(d => d.id)).toContain("d1");
      expect(list.map(d => d.id)).toContain("d2");
    });
  });

  describe("WorkflowEngine Delegation Methods", () => {
    it("should delegate startPipeline to workflowEngine", async () => {
      await service.startPipeline("draft-abc");
      expect(mockWorkflowEngine.executePipeline).toHaveBeenCalledWith("draft-abc");
    });

    it("should delegate pausePipeline to workflowEngine", async () => {
      await service.pausePipeline("draft-abc");
      expect(mockWorkflowEngine.pausePipeline).toHaveBeenCalledWith("draft-abc");
    });

    it("should delegate resumePipeline to workflowEngine", async () => {
      await service.resumePipeline("draft-abc");
      expect(mockWorkflowEngine.resumePipeline).toHaveBeenCalledWith("draft-abc");
    });

    it("should delegate cancelPipeline to workflowEngine", async () => {
      await service.cancelPipeline("draft-abc");
      expect(mockWorkflowEngine.cancelPipeline).toHaveBeenCalledWith("draft-abc");
    });

    it("should delegate retryStep to workflowEngine", async () => {
      await service.retryStep("draft-abc", "step-validate");
      expect(mockWorkflowEngine.executeStep).toHaveBeenCalledWith("draft-abc", "step-validate");
    });
  });

  describe("publishLesson", () => {
    it("should delegate publishLesson by dispatching PublishLessonCommand through commandDispatcher", async () => {
      fakeClock.currentTime = "2026-07-12T15:00:00Z";
      await service.publishLesson("draft-publish");

      expect(mockCommandDispatcher.dispatch).toHaveBeenCalledWith({
        commandId: "id-1",
        timestamp: "2026-07-12T15:00:00Z",
        type: "PublishLesson",
        draftId: "draft-publish"
      } as PublishLessonCommand);
    });
  });

  describe("duplicateDraft", () => {
    let original: LessonDraft;

    beforeEach(async () => {
      original = {
        id: "orig-123",
        schemaVersion: 1,
        aiModel: "gemini-3.5-flash",
        promptVersion: "1.0",
        pipelineState: PipelineState.COMPLETED,
        currentStepId: "save-lesson",
        steps: {
          "validate-vocabulary": { status: StepState.SUCCESS, retryCount: 0 }
        },
        context: {
          metadata: { level: "N3", lessonId: 15, titleVi: "Bài 15" },
          input: {
            vocabulary: [{ id: "v1", hiragana: "ねこ", romaji: "neko", meaningVi: "con mèo" }],
            grammar: []
          },
          validated: { vocabulary: [], grammar: [] },
          tokenized: { vocabularyTokens: {} },
          generated: { vocabularyWithMeanings: [], vocabularyWithExamples: [], grammarWithMeanings: [], grammarWithExamples: [], review: null }
        },
        createdById: "author-1",
        createdAt: "2026-07-01T00:00:00Z",
        updatedAt: "2026-07-01T00:00:00Z"
      };
      await fakeDraftRepository.create(original);
    });

    it("should duplicate a draft, resetting pipeline state and steps while cloning inputs", async () => {
      fakeClock.currentTime = "2026-07-12T16:00:00Z";
      const dup = await service.duplicateDraft("orig-123");

      expect(dup).toBeDefined();
      expect(dup.id).toBe("id-1"); // Generated
      expect(dup.pipelineState).toBe(PipelineState.DRAFT); // Reset
      expect(dup.currentStepId).toBeNull(); // Reset
      expect(dup.steps).toEqual({}); // Reset
      expect(dup.createdAt).toBe("2026-07-12T16:00:00Z"); // Updated
      expect(dup.updatedAt).toBe("2026-07-12T16:00:00Z"); // Updated
      expect(dup.context.input.vocabulary).toHaveLength(1); // Cloned
      expect(dup.context.input.vocabulary[0].hiragana).toBe("ねこ");

      // Verify original is untouched
      const origInDb = await fakeDraftRepository.getById("orig-123");
      expect(origInDb!.pipelineState).toBe(PipelineState.COMPLETED);
      expect(origInDb!.id).toBe("orig-123");

      // Verify dup in database
      const dupInDb = await fakeDraftRepository.getById("id-1");
      expect(dupInDb).not.toBeNull();
      expect(dupInDb!.pipelineState).toBe(PipelineState.DRAFT);
    });

    it("should throw BusinessError when duplicating a non-existent draft", async () => {
      await expect(service.duplicateDraft("non-existent")).rejects.toThrow(BusinessError);
    });
  });

  describe("archiveDraft", () => {
    let original: LessonDraft;

    beforeEach(async () => {
      original = {
        id: "orig-456",
        schemaVersion: 1,
        aiModel: "gemini-3.5-flash",
        promptVersion: "1.0",
        pipelineState: PipelineState.DRAFT,
        currentStepId: null,
        steps: {},
        context: {
          metadata: { level: "N3", lessonId: 15, titleVi: "Bài 15" },
          input: { vocabulary: [], grammar: [] },
          validated: { vocabulary: [], grammar: [] },
          tokenized: { vocabularyTokens: {} },
          generated: { vocabularyWithMeanings: [], vocabularyWithExamples: [], grammarWithMeanings: [], grammarWithExamples: [], review: null }
        },
        createdById: "author-1",
        createdAt: "2026-07-01T00:00:00Z",
        updatedAt: "2026-07-01T00:00:00Z"
      };
      await fakeDraftRepository.create(original);
    });

    it("should archive a draft by setting archived flag to true", async () => {
      fakeClock.currentTime = "2026-07-12T17:00:00Z";
      const archived = await service.archiveDraft("orig-456");

      expect(archived.archived).toBe(true);
      expect(archived.updatedAt).toBe("2026-07-12T17:00:00Z");

      const saved = await fakeDraftRepository.getById("orig-456");
      expect(saved!.archived).toBe(true);
      expect(saved!.updatedAt).toBe("2026-07-12T17:00:00Z");
    });

    it("should throw BusinessError when archiving a non-existent draft", async () => {
      await expect(service.archiveDraft("non-existent")).rejects.toThrow(BusinessError);
    });
  });

  describe("Real-time Watch Subscription & Unsubscribe Behavior", () => {
    let original: LessonDraft;

    beforeEach(async () => {
      original = {
        id: "draft-watch-123",
        schemaVersion: 1,
        aiModel: "gemini-3.5-flash",
        promptVersion: "1.0",
        pipelineState: PipelineState.DRAFT,
        currentStepId: null,
        steps: {},
        context: {
          metadata: { level: "N3", lessonId: 15, titleVi: "Bài 15" },
          input: { vocabulary: [], grammar: [] },
          validated: { vocabulary: [], grammar: [] },
          tokenized: { vocabularyTokens: {} },
          generated: { vocabularyWithMeanings: [], vocabularyWithExamples: [], grammarWithMeanings: [], grammarWithExamples: [], review: null }
        },
        createdById: "author-1",
        createdAt: "2026-07-01T00:00:00Z",
        updatedAt: "2026-07-01T00:00:00Z"
      };
      await fakeDraftRepository.create(original);
    });

    it("should watch draft updates and delegate to repository watch", () => {
      const spyWatch = vi.spyOn(fakeDraftRepository, "watch");
      const callback = vi.fn();

      const unsubscribe = service.watchDraft("draft-watch-123", callback);

      expect(spyWatch).toHaveBeenCalledWith("draft-watch-123", callback);
      expect(callback).toHaveBeenCalledWith(expect.objectContaining({ id: "draft-watch-123" }));
      expect(typeof unsubscribe).toBe("function");

      unsubscribe(); // Verify unsubscribe is executable and safe
    });
  });

  describe("Failure Propagation & Error Mapping", () => {
    it("should preserve original context of BaseWorkflowError and rethrow it unchanged", async () => {
      vi.spyOn(fakeDraftRepository, "getById").mockRejectedValue(new ValidationError("Simulated validation error"));

      await expect(service.getDraft("some-id")).rejects.toThrow(ValidationError);
      await expect(service.getDraft("some-id")).rejects.toThrowError("Simulated validation error");
    });

    it("should map native or third-party error to InfrastructureError while preserving stack/details", async () => {
      const nativeError = new Error("Firebase permission denied");
      vi.spyOn(fakeDraftRepository, "getById").mockRejectedValue(nativeError);

      try {
        await service.getDraft("some-id");
        expect.fail("Should have thrown");
      } catch (err: any) {
        expect(err).toBeInstanceOf(InfrastructureError);
        expect(err.code).toBe("INFRASTRUCTURE_ERROR");
        expect(err.message).toBe("Firebase permission denied");
        expect(err.details).toBe(nativeError); // Preserves original error context
      }
    });
  });
});
